steps:
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/line-webhook-pubsub, '.']
- name: gcr.io/cloud-builders/docker
  args: [tag, gcr.io/$PROJECT_ID/line-webhook-pubsub, gcr.io/$PROJECT_ID/line-webhook-pubsub:$TAG_NAME]

images:
- gcr.io/$PROJECT_ID/line-webhook-pubsub
- gcr.io/$PROJECT_ID/line-webhook-pubsub:$TAG_NAME
